
services:
  db:
    environment:
      MYSQL_ROOT_PASSWORD: qsor
      MYSQL_PASSWORD:      qsor

  app:
    environment:
      SECRET_KEY:  dev-secret-not-for-prod
      DB_PASSWORD: qsor
      APP_MODE:    dev
